# Generated by Django 4.1.7 on 2024-07-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0026_exercise_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='world',
            field=models.CharField(choices=[('none', 'None'), ('gazebo', 'Gazebo'), ('drones', 'Gazebo Drones'), ('gzsim', 'Gz Sim'), ('physical', 'Physical')], default='none', max_length=50),
        ),
    ]
